# Generated by Django 5.0.1 on 2024-01-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='studentId',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
